### ISSUE TITLE
Angular 8.x compatibility

### ISSUE THREAD

**Issue by laszlolukacs** [guillaume-ro-fr/ngx-country-picker#15]
The library seems to be working even with Angular 8.1.x, but I'll receive the following npm warnings:
`npm WARN ngx-country-picker@2.0.0 requires a peer of @angular/common@>=6.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by guillaume-ro-fr** [comment]
Released on 2.1.0
