### ISSUE TITLE
Remove git dependency

### ISSUE THREAD

**Issue by Booster2ooo** [guillaume-ro-fr/ngx-country-picker#16]
Hello,

I noticed there is a git based dependency for "world-countries" in [package.json](https://github.com/guillaume-ro-fr/ngx-country-picker/blob/master/package.json#L77).

I think it could simply be replaced by the npm one:
https://www.npmjs.com/package/world-countries

Best regards,

**Comment by guillaume-ro-fr** [comment]
Hello @Booster2ooo,

The npm package has not been updated for more than 10 months, and does not contain the latest changes, like the latest flags and country names (https://github.com/mledoze/countries/compare/v2.1.0...master).

It's the only reason for this decision and I agree with you that the use of the package is better, but I think that having up-to-date data is more important than a lighter node_modules folder on this case 😄 

When a new version is be released, I will change the package.json file 😉

**Comment by Booster2ooo** [comment]
It's out :) https://github.com/mledoze/countries/issues/360
