### ISSUE TITLE
ERROR TypeError: Cannot read property 'common' of undefined

### ISSUE THREAD

**Issue by trainincr** [guillaume-ro-fr/ngx-country-picker#3]
Hi,

I tried to use the ngx-country-picker, i follow the instruction but i when i run in my project the data not charge.
I think the problem is that it does not load the information from the countries.json, but if I load it by parameters the problem persists. 

`CountryPickerModule.forRoot({
      baseUrl: 'assets/',
      filename: 'countries.json'
    })`

html
`<ion-item>
          <ion-label>País</ion-label>
          <country-picker [flag]="false" [setValue]="cca3" [setName]="name.common"></country-picker>
        </ion-item>`

app.module.ts
`imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule.enablePersistence(),
    AngularFireAuthModule,
    CountryPickerModule.forRoot()
  ],`

**Comment by Lysergie** [comment]
I have the same problem.

**Comment by guillaume-ro-fr** [comment]
@jcastrillo @Lysergie : Do you have any errors in the console ? In the `Network` tab of your 
 browser DevTools, do you have a loading row for the `countries.json` file ?
For the `setName` and `setValue` directives, I think you have to put the value in quotes like : 

```html
<ion-item>
    <ion-label>País</ion-label>
    <country-picker [flag]="false" [setValue]="'cca3'" [setName]="'name.common'"></country-picker>
</ion-item>
```

Also, you can remove theirs directives if you don't modify the values 😉
